In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "https://msbooks.pk/"
response = requests.get(url)
html = response.text
soup = BeautifulSoup(html,"html.parser")

In [30]:
olevel_notes = soup.find("li",id="menu-item-73364")
olevel_notes_href = olevel_notes.find("a")["href"]
olevel_notes_href

'https://msbooks.pk/category/o-level-notes/'

In [4]:
olevel_notes_response = requests.get(olevel_notes_href)
olevel_notes_html = olevel_notes_response.text
olevel_notes_soup = BeautifulSoup(olevel_notes_html,"html.parser")

In [ ]:
notes = olevel_notes_soup.find_all("li",class_="product")
olevel_note_data = []
for note in notes:
    note_href = note.find("div",class_="woocommerce-loop-product__header").find("a")["href"]
    note_response = requests.get(note_href)
    note_html = note_response.text
    note_soup = BeautifulSoup(note_html,"html.parser")

    n = note_soup.find("div",class_="summary entry-summary")

    title = n.find("h1", class_="product_title entry-title").text
    price = n.find("p",class_="price").text
    price = int(price.replace(",","")[2:])

    attributes = n.find("div",class_="msbooks-attributes").find_all("p")
    missing_count = 0

    grade = attributes[0].text
    if "Grade: " in grade:
        grade = grade.replace("Grade: ","")
    else:
        grade = None
        missing_count += 1
    grade = grade.replace("LEVEL", "Level").replace("Levels", "Level")

    author = attributes[1-missing_count].text
    if "Author: " in author:
        author = author.replace("Author: ","")
    else:
        author = None
        missing_count +=1

    binding = attributes[2-missing_count].text
    if "Binding: " not in binding:
        missing_count += 1

    year = attributes[3-missing_count].text
    if "Year/Edition: " in year:
        year = year.replace("Year/Edition: ","")
    else:
        year = None
        missing_count += 1

    size = attributes[4-missing_count].text
    if "Size: " not in size:
        missing_count += 1
        
    code = attributes[5-missing_count].text
    if "Syllabus: " in code:
        code = code.replace("Syllabus: ","")
    else:
        code = None
        missing_count +=1

    type = attributes[6-missing_count].text
    if "Type: " in type:
        type = type.replace("Type: ","")
    else:
        type = None
        missing_count += 1
    type = type.replace("O Level","")

    olevel_note_data.append({
        "Title": title,
        "Subject code": code,
        "Author": author,
        "Grade": grade,
        "Type": type,
        "Edition": year,
        "Price": price
    })
olevel_note_data

[{'Title': 'O Level Add Math Notes by Rafique Akhtar',
  'Subject code': '4037',
  'Author': 'Rafique Akhtar',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2019-2020',
  'Price': 1350},
 {'Title': 'O Level Biology Notes by Abid Aziz',
  'Subject code': '5090',
  'Author': 'Abid Aziz',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2024-2025',
  'Price': 1500},
 {'Title': 'O Level Biology Notes by Dr. Sadia Khalid',
  'Subject code': '5090',
  'Author': 'Dr. Sadia Khalid',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2023-2025',
  'Price': 1550},
 {'Title': 'O Level Biology Notes by Hamza Fayyaz',
  'Subject code': None,
  'Author': 'Hamza Fayyaz',
  'Grade': 'O Level',
  'Type': 'O Level Notes',
  'Edition': '2021 Edition',
  'Price': 1350},
 {'Title': 'O Level Business Studies Notes by Tayyab Elahi',
  'Subject code': '7115',
  'Author': 'Tayyab Elahi',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2019',
  'Price': 1100},
 {'Title': 'O Level Chemistry Notes by Zafar Iqbal',
  'Subject code': '5070',
  'Author': 'Zafar Iqbal',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2019',
  'Price': 750},
 {'Title': 'O Level Computer Notes P1 & P2 by Navid Saqib',
  'Subject code': '2210',
  'Author': 'Navid Saqib',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2019',
  'Price': 1050},
 {'Title': 'O Level Economics Notes By Zubair Hussain',
  'Subject code': '2281',
  'Author': 'Zubair Hussain',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '1st Edition',
  'Price': 450},
 {'Title': 'O Level English Notes by Muavia Bashir Uppal',
  'Subject code': '1123',
  'Author': 'Muavia Bashir Uppal',
  'Grade': 'O LEVEL',
  'Type': 'O Level Notes',
  'Edition': '2020',
  'Price': 900},
 {'Title': 'O Level Geography by Faisal Salman',
  'Subject code': '2059',
  'Author': 'Faisal Salman',
  'Grade': 'O Levels',
  'Type': 'Notes',
  'Edition': '2023-2024',
  'Price': 900},
 {'Title': 'O Level Geography Notes by Dr. Iftikhar ul Haq',
  'Subject code': '2059',
  'Author': 'Dr. Iftikhar ul Haq',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '7th Edition',
  'Price': 900},
 {'Title': 'O Level Geography Notes by Dr. Usman Hameed',
  'Subject code': '2059',
  'Author': 'Dr. Usman Hameed',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2nd Edition',
  'Price': 1200},
 {'Title': 'O Level Geography Notes by Dr. Zubair Ahmed Bhatti',
  'Subject code': '2059',
  'Author': 'Dr. Zubair Ahmed Bhatti',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '1st Edition',
  'Price': 700},
 {'Title': 'O Level History Notes by Dr. Iftikhar ul Haq',
  'Subject code': '2059',
  'Author': 'Dr. Iftikhar ul Haq',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '7th Edition',
  'Price': 1150},
 {'Title': 'O Level History Notes by Dr. Usman Hameed',
  'Subject code': '2059',
  'Author': 'Dr. Usman Hameed',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2nd Edition',
  'Price': 1200},
 {'Title': 'O Level History Notes by Dr. Zubair Ahmed Bhatti',
  'Subject code': '2059',
  'Author': 'Dr. Zubair Ahmed Bhatti',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '1st Edition',
  'Price': 700},
 {'Title': 'O Level Islamiyat Notes by Ayesha Azhar',
  'Subject code': '2058',
  'Author': 'Ayesha Azhar',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '3rd Edition',
  'Price': 1200},
 {'Title': 'O Level Islamiyat Notes by Dr. Iftikhar ul Haq',
  'Subject code': '2058',
  'Author': 'Dr. Iftikhar ul Haq',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '7th Edition',
  'Price': 1550},
 {'Title': 'O Level Mathematics Notes by Rafique Akhtar',
  'Subject code': '4024',
  'Author': 'Rafique Akhtar',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2024-2025',
  'Price': 1950},
 {'Title': 'O Level Physics Notes by Hamiz javed',
  'Subject code': '5054',
  'Author': 'Hamiz Javed',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '1st Edition',
  'Price': 1200},
 {'Title': 'O Level Physics Notes by Mirza Irshad Baig',
  'Subject code': '5054',
  'Author': 'Mirza Irshad Baig',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': 'Edition 2024-2025',
  'Price': 500},
 {'Title': 'O Level Statistics Notes by Rafique Akhtar',
  'Subject code': '4040',
  'Author': 'Rafique Akhtar',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': '2019-2020',
  'Price': 1000},
 {'Title': 'O Level Urdu Notes by Zohair Latif',
  'Subject code': '3248',
  'Author': 'Zohair Latif',
  'Grade': 'O Level',
  'Type': 'Notes',
  'Edition': None,
  'Price': 800}]

In [ ]:
import pandas as pd
olevel_notes_df = pd.DataFrame(olevel_note_data)
olevel_notes_df

,Title,Subject code,Author,Grade,Type,Edition,Price
0,O Level Add Math Notes by Rafique Akhtar,4037,Rafique Akhtar,O Level,Notes,2019-2020,1350
1,O Level Biology Notes by Abid Aziz,5090,Abid Aziz,O Level,Notes,2024-2025,1500
2,O Level Biology Notes by Dr. Sadia Khalid,5090,Dr. Sadia Khalid,O Level,Notes,2023-2025,1550
3,O Level Biology Notes by Hamza Fayyaz,NaN,Hamza Fayyaz,O Level,O Level Notes,2021 Edition,1350
4,O Level Business Studies Notes by Tayyab Elahi,7115,Tayyab Elahi,O Level,Notes,2019,1100
5,O Level Chemistry Notes by Zafar Iqbal,5070,Zafar Iqbal,O Level,Notes,2019,750
6,O Level Computer Notes P1 & P2 by Navid Saqib,2210,Navid Saqib,O Level,Notes,2019,1050
7,O Level Economics Notes By Zubair Hussain,2281,Zubair Hussain,O Level,Notes,1st Edition,450
8,O Level English Notes by Muavia Bashir Uppal,1123,Muavia Bashir Uppal,O LEVEL,O Level Notes,2020,900
9,O Level Geography by Faisal Salman,2059,Faisal Salman,O Levels,Notes,2023-2024,900
10,O Level Geography Notes by Dr. Iftikhar ul Haq,2059,Dr. Iftikhar ul Haq,O Level,Notes,7th Edition,900
11,O Level Geography Notes by Dr. Usman Hameed,2059,Dr. Usman Hameed,O Level,Notes,2nd Edition,1200
12,O Level Geography Notes by Dr. Zubair Ahmed Bh...,2059,Dr. Zubair Ahmed Bhatti,O Level,Notes,1st Edition,700
13,O Level History Notes by Dr. Iftikhar ul Haq,2059,Dr. Iftikhar ul Haq,O Level,Notes,7th Edition,1150
14,O Level History Notes by Dr. Usman Hameed,2059,Dr. Usman Hameed,O Level,Notes,2nd Edition,1200
15,O Level History Notes by Dr. Zubair Ahmed Bhatti,2059,Dr. Zubair Ahmed Bhatti,O Level,Notes,1st Edition,700
16,O Level Islamiyat Notes by Ayesha Azhar,2058,Ayesha Azhar,O Level,Notes,3rd Edition,1200
17,O Level Islamiyat Notes by Dr. Iftikhar ul Haq,2058,Dr. Iftikhar ul Haq,O Level,Notes,7th Edition,1550
18,O Level Mathematics Notes by Rafique Akhtar,4024,Rafique Akhtar,O Level,Notes,2024-2025,1950
19,O Level Physics Notes by Hamiz javed,5054,Hamiz Javed,O Level,Notes,1st Edition,1200
20,O Level Physics Notes by Mirza Irshad Baig,5054,Mirza Irshad Baig,O Level,Notes,Edition 2024-2025,500
21,O Level Statistics Notes by Rafique Akhtar,4040,Rafique Akhtar,O Level,Notes,2019-2020,1000
22,O Level Urdu Notes by Zohair Latif,3248,Zohair Latif,O Level,Notes,NaN,800

In [31]:
olevel_topicals = soup.find("li",id="menu-item-73369")
olevel_topicals_href = olevel_topicals.find("a")["href"]
olevel_topicals_href

'https://msbooks.pk/category/o-level-unsolved-topical/'

In [32]:
olevel_topicals_response = requests.get(olevel_topicals_href)
olevel_topicals_html = olevel_topicals_response.text
olevel_topicals_soup = BeautifulSoup(olevel_topicals_html,"html.parser")

In [ ]:
topicals = olevel_topicals_soup.find_all("li",class_="product")
olevel_topical_data = []
for topical in topicals:
    topical_href = topical.find("div",class_="woocommerce-loop-product__header").find("a")["href"]
    topical_response = requests.get(topical_href)
    topical_html = topical_response.text
    topical_soup = BeautifulSoup(topical_html,"html.parser")

    t = topical_soup.find("div",class_="summary entry-summary")

    title = t.find("h1", class_="product_title entry-title").text
    price = t.find("p",class_="price").text
    price = int(price.replace(",","")[2:])

    attributes = t.find("div",class_="msbooks-attributes").find_all("p")
    missing_count = 0

    grade = attributes[0].text
    if "Grade: " in grade:
        grade = grade.replace("Grade: ","")
    else:
        grade = None
        missing_count += 1
    grade = grade.replace("LEVEL", "Level").replace("Levels", "Level")

    author = attributes[1-missing_count].text
    if "Author: " in author:
        author = author.replace("Author: ","")
    else:
        author = None
        missing_count +=1

    binding = attributes[2-missing_count].text
    if "Binding: " not in binding:
        missing_count += 1

    year = attributes[3-missing_count].text
    if "Year/Edition: " in year:
        year = year.replace("Year/Edition: ","")
    else:
        year = None
        missing_count += 1

    size = attributes[4-missing_count].text
    if "Size: " not in size:
        missing_count += 1
        
    code = attributes[5-missing_count].text
    if "Syllabus: " in code:
        code = code.replace("Syllabus: ","")
    else:
        code = None
        missing_count +=1

    type = attributes[6-missing_count].text
    if "Type: " in type:
        type = type.replace("Type: ","")
    else:
        type = None
        missing_count += 1
    type = type.replace(" with Mark Scheme","").replace(" with Marking Schemes","")

    olevel_topical_data.append({
        "Title": title,
        "Subject code": code,
        "Author": author,
        "Grade": grade,
        "Type": type,
        "Edition": year,
        "Price": price
    })
olevel_topical_data

[{'Title': 'O-L Unsolved Topical Accounting Paper 1 (2025-2026 Edition)',
  'Subject code': '7707',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S20-W24',
  'Price': 1100},
 {'Title': 'O-L Unsolved Topical Accounting Paper 2 (2025-2026 Edition)',
  'Subject code': '7707',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S20-W24',
  'Price': 1550},
 {'Title': 'O-L Unsolved Topical Biology Paper 1 (2025-2026 Edition)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1250},
 {'Title': 'O-L Unsolved Topical Biology Paper 2 (2025-2026 Edition)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1700},
 {'Title': 'O-L Unsolved Topical Biology Paper 4 (2025-2026 Edition)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1950},
 {'Title': 'O-L Unsolved Topical Business Studies Paper 1 (2025-2026 Edition)',
  'Subject code': '7115',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 2150},
 {'Title': 'O-L Unsolved Topical Business Studies Paper 2 (2025-2026 Edition)',
  'Subject code': '7115',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 2400},
 {'Title': 'O-L Unsolved Topical Chemistry Paper 1 (2025-2026 Edition)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1200},
 {'Title': 'O-L Unsolved Topical Chemistry Paper 2 (2025-2026 Edition)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1700},
 {'Title': 'O-L Unsolved Topical Chemistry Paper 4 (2025-2026 Edition)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1300},
 {'Title': 'O-L Unsolved Topical Computer Science Paper 1 (2025-2026 Edition)',
  'Subject code': '2210/0478',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S21-W24',
  'Price': 1300},
 {'Title': 'O-L Unsolved Topical Computer Science Paper 2 (2025-2026 Edition)',
  'Subject code': '2210/0478',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S21-W24',
  'Price': 1400},
 {'Title': 'O-L Unsolved Topical Economics Paper 1 (2025-2026 Edition)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Marking Schemes',
  'Edition': '2025-2026',
  'Price': 1200},
 {'Title': 'O-L Unsolved Topical Geography Paper 2 (2025-2026 Edition)',
  'Subject code': '2059',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 2050},
 {'Title': 'O-L Unsolved Topical History Paper 1 (2025-2026 Edition)',
  'Subject code': '2059',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1800},
 {'Title': 'O-L Unsolved Topical MACRO Economics Paper 2  (2025-2026 Edition)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical With Marking Schemes',
  'Edition': 'S17-W24',
  'Price': 2000},
 {'Title': 'O-L Unsolved Topical Mathematics Paper 1 (2025-2026 Edition)',
  'Subject code': '4024',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 2100},
 {'Title': 'O-L Unsolved Topical Mathematics Paper 2 (2025-2026 Edition)',
  'Subject code': '4024',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 2000},
 {'Title': 'O-L Unsolved Topical MICRO Economics Paper 2 (2025-2026 Edition)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Marking Schemes',
  'Edition': 'S17-W24',
  'Price': 1600},
 {'Title': 'O-L Unsolved Topical Physics Paper 1 (2025-2026 Edition)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1150},
 {'Title': 'O-L Unsolved Topical Physics Paper 2 (2025-2026 Edition)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 2250},
 {'Title': 'O-L Unsolved Topical Physics Paper 4 (2025-2026 Edition)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S17-W24',
  'Price': 1450},
 {'Title': 'OL Unsolved Topical Islamiyat Paper 1 (2025-2026 Edition)',
  'Subject code': '2058',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S14-W24',
  'Price': 1750},
 {'Title': 'OL Unsolved Topical Islamiyat Paper 2 (2025-2026 Edition)',
  'Subject code': '2058',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Unsolved Topical with Mark Scheme',
  'Edition': 'S14-W24',
  'Price': 1700}]

In [34]:
olevel_topicals_df = pd.DataFrame(olevel_topical_data)
olevel_topicals_df

,Title,Subject code,Author,Grade,Type,Edition,Price
0,O-L Unsolved Topical Accounting Paper 1 (2025-...,7707,None,O Level,Unsolved Topical with Mark Scheme,S20-W24,1100
1,O-L Unsolved Topical Accounting Paper 2 (2025-...,7707,None,O Level,Unsolved Topical with Mark Scheme,S20-W24,1550
2,O-L Unsolved Topical Biology Paper 1 (2025-202...,5090,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1250
3,O-L Unsolved Topical Biology Paper 2 (2025-202...,5090,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1700
4,O-L Unsolved Topical Biology Paper 4 (2025-202...,5090,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1950
5,O-L Unsolved Topical Business Studies Paper 1 ...,7115,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,2150
6,O-L Unsolved Topical Business Studies Paper 2 ...,7115,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,2400
7,O-L Unsolved Topical Chemistry Paper 1 (2025-2...,5070,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1200
8,O-L Unsolved Topical Chemistry Paper 2 (2025-2...,5070,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1700
9,O-L Unsolved Topical Chemistry Paper 4 (2025-2...,5070,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1300
10,O-L Unsolved Topical Computer Science Paper 1 ...,2210/0478,None,O Level,Unsolved Topical with Mark Scheme,S21-W24,1300
11,O-L Unsolved Topical Computer Science Paper 2 ...,2210/0478,None,O Level,Unsolved Topical with Mark Scheme,S21-W24,1400
12,O-L Unsolved Topical Economics Paper 1 (2025-2...,2281,None,O Level,Unsolved Topical with Marking Schemes,2025-2026,1200
13,O-L Unsolved Topical Geography Paper 2 (2025-2...,2059,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,2050
14,O-L Unsolved Topical History Paper 1 (2025-202...,2059,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1800
15,O-L Unsolved Topical MACRO Economics Paper 2 ...,2281,None,O Level,Unsolved Topical With Marking Schemes,S17-W24,2000
16,O-L Unsolved Topical Mathematics Paper 1 (2025...,4024,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,2100
17,O-L Unsolved Topical Mathematics Paper 2 (2025...,4024,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,2000
18,O-L Unsolved Topical MICRO Economics Paper 2 (...,2281,None,O Level,Unsolved Topical with Marking Schemes,S17-W24,1600
19,O-L Unsolved Topical Physics Paper 1 (2025-202...,5054,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1150
20,O-L Unsolved Topical Physics Paper 2 (2025-202...,5054,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,2250
21,O-L Unsolved Topical Physics Paper 4 (2025-202...,5054,None,O Level,Unsolved Topical with Mark Scheme,S17-W24,1450
22,OL Unsolved Topical Islamiyat Paper 1 (2025-20...,2058,None,O Level,Unsolved Topical with Mark Scheme,S14-W24,1750
23,OL Unsolved Topical Islamiyat Paper 2 (2025-20...,2058,None,O Level,Unsolved Topical with Mark Scheme,S14-W24,1700

In [5]:
olevel_yearly = soup.find("li",id="menu-item-73366")
olevel_yearly_href = olevel_yearly.find("a")["href"]
olevel_yearly_href

'https://msbooks.pk/category/yearly-unsolved-past-papers-o/'

In [6]:
olevel_yearly_response = requests.get(olevel_yearly_href)
olevel_yearly_html = olevel_yearly_response.text
olevel_yearly_soup = BeautifulSoup(olevel_yearly_html,"html.parser")

In [7]:
olevel_yearly_data = []
while True:
    yearlys = olevel_yearly_soup.find_all("li",class_="product")
    print ("Products in page:",len(yearlys))
    for yearly in yearlys:
        yearly_href = yearly.find("div",class_="woocommerce-loop-product__header").find("a")["href"]
        yearly_response = requests.get(yearly_href)
        yearly_html = yearly_response.text
        yearly_soup = BeautifulSoup(yearly_html,"html.parser")

        y = yearly_soup.find("div",class_="summary entry-summary")

        title = y.find("h1", class_="product_title entry-title").text
        price = y.find("p",class_="price").text
        price = int(price.replace(",","")[2:])

        attributes = y.find("div",class_="msbooks-attributes").find_all("p")
        missing_count = 0

        grade = attributes[0].text
        if "Grade: " in grade:
            grade = grade.replace("Grade: ","")
        else:
            grade = None
            missing_count += 1
        grade = grade.replace("LEVEL", "Level").replace("Levels", "Level")

        author = attributes[1-missing_count].text
        if "Author: " in author:
            author = author.replace("Author: ","")
        else:
            author = None
            missing_count +=1

        binding = attributes[2-missing_count].text
        if "Binding: " not in binding:
            missing_count += 1

        year = attributes[3-missing_count].text
        if "Year/Edition: " in year:
            year = year.replace("Year/Edition: ","")
        else:
            year = None
            missing_count += 1

        size = attributes[4-missing_count].text
        if "Size: " not in size:
            missing_count += 1
            
        code = attributes[5-missing_count].text
        if "Syllabus: " in code:
            code = code.replace("Syllabus: ","")
        else:
            code = None
            missing_count +=1

        type = attributes[6-missing_count].text
        if "Type: " in type:
            type = type.replace("Type: ","")
        else:
            type = None
            missing_count += 1
        type = type.replace(" with Mark Scheme","").replace(" with Marking Schemes","")

        olevel_yearly_data.append({
            "Title": title,
            "Subject code": code,
            "Author": author,
            "Grade": grade,
            "Type": type,
            "Edition": year,
            "Price": price
        })
    next_btn = olevel_yearly_soup.find("a",class_="next")
    if not next_btn:
        break
    else:
        next_url = next_btn["href"]
        next_response = requests.get(next_url)
        next_html = next_response.text
        olevel_yearly_soup = BeautifulSoup(next_html,"html.parser")

olevel_yearly_data

Products in page: 30
Products in page: 30
Products in page: 29

[{'Title': 'O Leve Yearly Unsolved English Language Paper 2 Writing (S15-W19)',
  'Subject code': '1123',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1500},
 {'Title': 'O Level Travel & Tour Paper 1 (W21-W25)',
  'Subject code': '7096',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W21-W25',
  'Price': 900},
 {'Title': 'O Level Travel & Tour Paper 2 (W21-W25)',
  'Subject code': '7096',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W21-W25',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Accounting Paper 1 (S15-W19)',
  'Subject code': '7110',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 650},
 {'Title': 'O Level Yearly Unsolved Accounting Paper 1 (S21-W25)',
  'Subject code': '7707',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved Accounting Paper 2 (S15-W19)',
  'Subject code': '9110',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1900},
 {'Title': 'O Level Yearly Unsolved Accounting Paper 2 (S21-W25)',
  'Subject code': '7707',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1600},
 {'Title': 'O Level Yearly Unsolved Add Maths Paper 1 (S21-W25)',
  'Subject code': '4037',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1550},
 {'Title': 'O Level Yearly Unsolved Add Maths Paper 2 (S21-W25)',
  'Subject code': '4037',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1600},
 {'Title': 'O Level Yearly Unsolved AddMaths Paper 1 (S15-W19)',
  'Subject code': '4037',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1550},
 {'Title': 'O Level Yearly Unsolved AddMaths Paper 2 (S15-W19)',
  'Subject code': '4037',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1450},
 {'Title': 'O Level Yearly Unsolved Biology Paper 1 (S15-W19)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1000},
 {'Title': 'O Level Yearly Unsolved Biology Paper 1 (S21-W25)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1150},
 {'Title': 'O Level Yearly Unsolved Biology Paper 2 (S15-W19)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1500},
 {'Title': 'O Level Yearly Unsolved Biology Paper 2 (S21-W25)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1200},
 {'Title': 'O Level Yearly Unsolved Biology Paper 4 (S21-W25)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 700},
 {'Title': 'O Level Yearly Unsolved Biology Paper 6 (S15-W19)',
  'Subject code': '5090',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 850},
 {'Title': 'O Level Yearly Unsolved Business Studies Paper 1 (S15-W19)',
  'Subject code': '7115',
  'Author': None,
  'Grade': 'O level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W24',
  'Price': 1500},
 {'Title': 'O Level Yearly Unsolved Business Studies Paper 1(S21-W25)',
  'Subject code': '7115',
  'Author': None,
  'Grade': 'O level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1200},
 {'Title': 'O Level Yearly Unsolved Business Studies Paper 2 (S15-W19)',
  'Subject code': '7115',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W24',
  'Price': 1450},
 {'Title': 'O Level Yearly Unsolved Business Studies Paper 2 (S21-W25)',
  'Subject code': '7115',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1750},
 {'Title': 'O Level Yearly Unsolved Chemistry Paper 1 (S15-W18)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 700},
 {'Title': 'O Level Yearly Unsolved Chemistry Paper 1 (S19-W25)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S19-W25',
  'Price': 1400},
 {'Title': 'O Level Yearly Unsolved Chemistry Paper 2 (S15-W19)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1550},
 {'Title': 'O Level Yearly Unsolved Chemistry Paper 2 (S20-W25)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-W25',
  'Price': 1550},
 {'Title': 'O Level Yearly Unsolved Chemistry Paper 4 (S15-W19)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1200},
 {'Title': 'O Level Yearly Unsolved Chemistry Paper 4 (S21-W25)',
  'Subject code': '5070',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-S25',
  'Price': 900},
 {'Title': 'O Level Yearly Unsolved Combined Science Paper 1 (S15-W19)',
  'Subject code': '5129',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1050},
 {'Title': 'O Level Yearly Unsolved Combined Science Paper 1 (S21-W25)',
  'Subject code': '5129',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1050},
 {'Title': 'O Level Yearly Unsolved Combined Science Paper 2 (S15-W19)',
  'Subject code': '5129',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 2050},
 {'Title': 'O Level Yearly Unsolved Combined Science Paper 2 (S21-W25)',
  'Subject code': '5129',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1500},
 {'Title': 'O Level Yearly Unsolved Commerce Paper 1 (S15-W19)',
  'Subject code': '7100',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 700},
 {'Title': 'O Level Yearly Unsolved Commerce Paper 1 (S21-W25)',
  'Subject code': '7100',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved Commerce Paper 2 (S15-W19)',
  'Subject code': '7100',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1550},
 {'Title': 'O Level Yearly Unsolved Commerce Paper 2 (S21-W25)',
  'Subject code': '7100',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1300},
 {'Title': 'O Level Yearly Unsolved Computer Science Paper 1 (S15-W19)',
  'Subject code': '2210',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1450},
 {'Title': 'O Level Yearly Unsolved Computer Science Paper 1 (S21-W25)',
  'Subject code': '2210',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 950},
 {'Title': 'O Level Yearly Unsolved Computer Science Paper 2 (S15-W19)',
  'Subject code': '2210',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1250},
 {'Title': 'O Level Yearly Unsolved Computer Science Paper 2 (S21-W25)',
  'Subject code': '2210',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1200},
 {'Title': 'O Level Yearly Unsolved Economics Paper 1 (S15-W19)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 650},
 {'Title': 'O Level Yearly Unsolved Economics Paper 1 (S21-W25)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 700},
 {'Title': 'O Level Yearly Unsolved Economics Paper 2 (S15-W19)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1300},
 {'Title': 'O Level Yearly Unsolved Economics Paper 2 (S21-W25)',
  'Subject code': '2281',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved English Language P1 Reading (S21-W25)',
  'Subject code': '1123',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1500},
 {'Title': 'O Level Yearly Unsolved English Language P2 Writing  (S21-W25)',
  'Subject code': '1123',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved English Language Paper 1 Reading (S15-W19)',
  'Subject code': '1123',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved English Literature Paper 1  (S21-W25)',
  'Subject code': '2010',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1650},
 {'Title': 'O Level Yearly Unsolved English Literature Paper 1 (S15-W19)',
  'Subject code': '2010',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1850},
 {'Title': 'O Level Yearly Unsolved English Literature Paper 2  (S15-W19)',
  'Subject code': '2010',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 950},
 {'Title': 'O Level Yearly Unsolved English Literature Paper 2 (S21-W25)',
  'Subject code': '2010',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Environmental Management Paper 1 (S15-W19)',
  'Subject code': '5014',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 2250},
 {'Title': 'O Level Yearly Unsolved Environmental Management Paper 1 (S21-W25)',
  'Subject code': '5014',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved Environmental Management Paper 2 (S15-W19)',
  'Subject code': '5014',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1450},
 {'Title': 'O Level Yearly Unsolved Environmental Management Paper 2 (S21-W25)',
  'Subject code': '5014',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Food & Nutrition Paper 1 & 2 (S15-W19)',
  'Subject code': '6065',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1600},
 {'Title': 'O Level Yearly Unsolved Food & Nutrition Paper 1 & 2 (S21-W25)',
  'Subject code': '6065',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1800},
 {'Title': 'O Level Yearly Unsolved Geography Paper 2 (S15-W19)',
  'Subject code': '2059',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1350},
 {'Title': 'O Level Yearly Unsolved Geography Paper 2 (S20-W25)',
  'Subject code': '2059',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-W25',
  'Price': 1950},
 {'Title': 'O Level Yearly Unsolved Global Prescriptive Paper 1 (S20-S25)',
  'Subject code': '2069',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-S25',
  'Price': 650},
 {'Title': 'O Level Yearly Unsolved History Paper 1 (S15-W19)',
  'Subject code': '2059',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 600},
 {'Title': 'O Level Yearly Unsolved History Paper 1 (S21-W25)',
  'Subject code': '2059',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 500},
 {'Title': 'O Level Yearly Unsolved Islamiyat Paper 1 (S15-W19)',
  'Subject code': '2058',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1800},
 {'Title': 'O Level Yearly Unsolved Islamiyat Paper 1 (S21-W25)',
  'Subject code': '2058',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1900},
 {'Title': 'O Level Yearly Unsolved Islamiyat Paper 2 (S15-W19)',
  'Subject code': '2058',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1600},
 {'Title': 'O Level Yearly Unsolved Islamiyat Paper 2 (S21-W25)',
  'Subject code': '2058',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1800},
 {'Title': 'O Level Yearly Unsolved Mathematics Paper 1 (S15-W19)',
  'Subject code': '4024',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1600},
 {'Title': 'O Level Yearly Unsolved Mathematics Paper 1 (S20-W25)',
  'Subject code': '4024',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-W25',
  'Price': 1800},
 {'Title': 'O Level Yearly Unsolved Mathematics Paper 2 (S15-W19)',
  'Subject code': '4024',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1750},
 {'Title': 'O Level Yearly Unsolved Mathematics Paper 2 (S20-W25)',
  'Subject code': '4024',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-W25',
  'Price': 2000},
 {'Title': 'O Level Yearly Unsolved Physics Paper 1 (S15-W19)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Physics Paper 1 (S19-W25)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S19-W25',
  'Price': 1450},
 {'Title': 'O Level Yearly Unsolved Physics Paper 2  (S20-W25)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S20-W25',
  'Price': 1650},
 {'Title': 'O Level Yearly Unsolved Physics Paper 2 (S15-W19)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1600},
 {'Title': 'O Level Yearly Unsolved Physics Paper 4  (S15-W19)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Physics Paper 4 (S21-W25)',
  'Subject code': '5054',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 950},
 {'Title': 'O Level Yearly Unsolved Sociology Paper 1 (S15-W19)',
  'Subject code': '2251',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1250},
 {'Title': 'O Level Yearly Unsolved Sociology Paper 1 (S21-W25)',
  'Subject code': '2251',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 700},
 {'Title': 'O Level Yearly Unsolved Sociology Paper 2 (S15-W19)',
  'Subject code': '2251',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W19',
  'Price': 1700},
 {'Title': 'O Level Yearly Unsolved Sociology Paper 2 (S21-W25)',
  'Subject code': '2251',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 950},
 {'Title': 'O Level Yearly Unsolved Statistics Paper 1 (W15-W19)',
  'Subject code': '4040',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W15-W19',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Statistics Paper 1 (W21-W25)',
  'Subject code': '4040',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W21-W25',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved Statistics Paper 2 (W15-W19)',
  'Subject code': '4040',
  'Author': None,
  'Grade': 'O level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W15-W19',
  'Price': 750},
 {'Title': 'O Level Yearly Unsolved Statistics Paper 2 (W20-W24)',
  'Subject code': '4040',
  'Author': None,
  'Grade': 'O level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W20-W24',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Travel & Tour Paper 1 (W15-W19)',
  'Subject code': '7096',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W15-W19',
  'Price': 850},
 {'Title': 'O Level Yearly Unsolved Travel & Tour Paper 2 (W15-W19)',
  'Subject code': '7096',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'W15-W19',
  'Price': 800},
 {'Title': 'O Level Yearly Unsolved Urdu A Paper 1 & 2  (S21-S25)',
  'Subject code': '3247',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-S25',
  'Price': 550},
 {'Title': 'O Level Yearly Unsolved Urdu A Paper 1 & 2 (S14-S24)',
  'Subject code': '3247',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S14-S24',
  'Price': 900},
 {'Title': 'O Level Yearly Unsolved Urdu B Paper 1 & 2 (S15-W24)',
  'Subject code': '3248',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S15-W24',
  'Price': 2050},
 {'Title': 'O Level Yearly Unsolved Urdu B Paper 1 & 2 (S21-W25)',
  'Subject code': '3248',
  'Author': None,
  'Grade': 'O Level',
  'Type': 'Yearly Unsolved',
  'Edition': 'S21-W25',
  'Price': 1000}]

In [ ]:
olevel_yearly_df = pd.DataFrame(olevel_yearly_data)
olevel_yearly_df

,Title,Subject code,Author,Grade,Type,Edition,Price
0,O Leve Yearly Unsolved English Language Paper ...,1123,None,O Level,Yearly Unsolved,S15-W19,1500
1,O Level Travel & Tour Paper 1 (W21-W25),7096,None,O Level,Yearly Unsolved,W21-W25,900
2,O Level Travel & Tour Paper 2 (W21-W25),7096,None,O Level,Yearly Unsolved,W21-W25,800
3,O Level Yearly Unsolved Accounting Paper 1 (S1...,7110,None,O Level,Yearly Unsolved,S15-W19,650
4,O Level Yearly Unsolved Accounting Paper 1 (S2...,7707,None,O Level,Yearly Unsolved,S21-W25,750
...,...,...,...,...,...,...,...
84,O Level Yearly Unsolved Travel & Tour Paper 2 ...,7096,None,O Level,Yearly Unsolved,W15-W19,800
85,O Level Yearly Unsolved Urdu A Paper 1 & 2 (S...,3247,None,O Level,Yearly Unsolved,S21-S25,550
86,O Level Yearly Unsolved Urdu A Paper 1 & 2 (S1...,3247,None,O Level,Yearly Unsolved,S14-S24,900
87,O Level Yearly Unsolved Urdu B Paper 1 & 2 (S1...,3248,None,O Level,Yearly Unsolved,S15-W24,2050
88,O Level Yearly Unsolved Urdu B Paper 1 & 2 (S2...,3248,None,O Level,Yearly Unsolved,S21-W25,1000

In [3]:
alevel = soup.find("li",id="menu-item-73355")
alevel_href = alevel.find("a")["href"]
alevel_href

'https://msbooks.pk/category/a-levels/'

In [4]:
igcse = soup.find("li",id="menu-item-73359")
igcse_href = igcse.find("a")["href"]
igcse_href

'https://msbooks.pk/category/igcse/'

In [5]:
olevel = soup.find("li",id="menu-item-73353")
olevel_href = olevel.find("a")["href"]
olevel_href

'https://msbooks.pk/category/o-levels/'